rss_settings:
  label: RSS Feed
  fields:
    title:
      type: string
      hint: "Titel van de podcast"
      label: "Titel"
      required: true
    subtitle:
      type: string
      hint: "Subtitel voor iTunes feed"
      label: "Subtitel"
      required: true
    description:
      type: text
      hint: "Omschrijving voor iTunes feed. Iets uitgebreider dan de subtitel"
      label: "Omschrijving"
      required: true
    cover_art:
      type: image
      required: true
      label: "Cover art"
      hint: "Cover art voor podcast. Moet 3000x3000 en goed geoptimaliseerd zijn!"
    language:
      type: select
      select_options: ["nl", "en-us"]
      hint: "Taal van podcast"
      label: "Taal"
      required: true
      text_formatting: text
    link:
      type: string
      hint: "Link naar podcast pagina (bijv. https://www.apple.com/itunes/podcasts/)"
      required: true
    copyright:
      type: string
      hint: "Bijv. &#8471; &amp; &#xA9; 2017 John Appleseed"
      required: true
    owner_name:
      type: string
      label: Eigenaar
      hint: "Eigenaar van podcast feed"
      required: true
    owner_email:
      type: string
      label: Email adres eigenaar
      required: true
    explicit:
      type: boolean
      label: Grof taalgebruik
      hint: "Default 'explicit' setting"
    type:
      type: select
      select_options: ["serial", "episodic"]
      label: iTunes type
      required: true
    author:
      type: string
      label: Auteur
      hint: Auteur van podcast
      required: true

social_media:
  label: Social Media
  fields:
    youtube_url:
      type: string
      label: YouTube URL
    facebook_url:
      type: string
      label: Facebook URL
    twitter_url:
      type: string
      label: Twitter URL
    instagram_url:
      type: string
      label: Instagram URL
    itunes_url:
      type: string
      label: iTunes URL
    rss_url:
      type: string
      label: RSS URL

misc_settings:
  label: Overig
  fields:
    autoplay:
      type: boolean
      label: YouTube Autoplay
      hint: Autoplay YouTube video op de podcast pagina
