# The name of this site
# This text displays in the back-office and
# can be used in templates through the site.name global variable
name: "filmerds"

# An array of domain aliases for the site
# This option is for sites on multi-site engines
# domains: [www.example.com, example.com]

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [nl]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
timezone: Amsterdam

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
seo_title: Filmerds
meta_keywords: "some meta keywords"
meta_description: "Een podcast voor en door liefhebbers van film!"

metafields:
  rss_settings:
    title: Filmerds
    cover_art: "/samples/assets/filmerds_logo_3000-min.png"
    language: nl
    link: https://www.filmerds.com/
    subtitle: Een podcast voor en door liefhebbers van film!
    copyright: "&#xA9; 2019 Filmerds"
    owner_name: Sander Schekman
    owner_email: aaschekman@icloud.com
    explicit: '1'
    type: episodic
    author: Sander Schekman, Henk van der Velden en Pim Meijerman
    description: Filmerds is een maandelijkse podcast voor en door liefhebbers van
      film! We brengen maandelijks een lange podcast uit, met daarin reviews en andere
      film gerelateerde content. Ook nemen wij de aankomende releases door in samenwerking
      met Filmdomein. Naast deze lange podcast kan je ook speciale afleveringen van
      ons verwachten. Toffe samenwerkingen, rare lijstjes, pittige spelletjes en andere
      formats. Dus hou onze social media in de gaten!
  misc_settings:
    autoplay: '0'
    production: '1'
    bio: '0'
    site_verification_code: _XmBQbPrFj1LCIIySJsqTaQQFBGagbXfDf99yHV5eFY
  social_media:
    youtube_url: https://www.youtube.com/channel/UCQtXVEMsLDGNCdoJ9TmCLJg
    facebook_url: https://www.facebook.com/Filmerds/
    twitter_url: https://twitter.com/Filmerds
    instagram_url: https://instagram.com/Filmerds
    itunes_url: https://itunes.apple.com/nl/podcast/filmerds-podcast/id1098182855?mt=2
    rss_url: https://filmerds.com/rss
